#!/bin/bash

printf "Compile Script \nThis compile script builds and compiles the module before putting it into a mock project in ./test\n"

npm ci

printf "Finished getting deps\n"x

npx tsc --outDir ./dist/es6 -m es6
npx tsc --outDir ./dist/commonjs -m commonjs

mv ./dist/es6/index.js ./dist/es6/index.mjs
mv ./dist/commonjs/index.js ./dist/commonjs/index.cjs

printf "Finished compiling\n"

exit 0